# Site settings
title: Kyle's Corner
email:
description: The science of prediction 
baseurl:
url:
twitter_username: 
github_username:  kairusann

exclude: ["basic_charts", "example","*.zip","*.7z"]

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true
